name: ci
on:
  push:
jobs:
  build-and-check:
    permissions:
      contents: read
      deployments: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm playwright test

      - name: Generate coverage report
        run: pnpm test:coverage-report

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: test/coverage/html/lcov.info
          minimum-coverage: 70
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Deploy
        run: pnpm release
        env:
          PARTYKIT_TOKEN: ${{ secrets.PARTYKIT_TOKEN }}
          PARTYKIT_LOGIN: hasparus
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

      - name: Create GitHub Preview Deployment
        if: github.ref_name != 'main'
        uses: chrnorm/deployment-action@v2
        with:
          token: "${{ github.token }}"
          # env.DEPLOYMENT_URL is set by ./scripts/deploy.sh
          environment-url: https://${{ env.DEPLOYMENT_URL }}
          environment: Preview
          production-environment: false
          initial-status: success

      - name: Create GitHub Production Deployment
        if: github.ref_name == 'main'
        uses: chrnorm/deployment-action@v2
        with:
          token: "${{ github.token }}"
          environment-url: https://${{ env.DEPLOYMENT_URL }}
          environment: Production
          production-environment: true
          initial-status: success
