name: e2e
on:
  pull_request:
jobs:
  playwright:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm playwright test

      - name: Generate coverage report
        if: always()
        run: pnpm test:coverage-report

      - name: Install lcov
        if: always()
        run: sudo apt-get install -y lcov

      - name: Report code coverage
        if: always()
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: test/coverage/html/lcov.info
          minimum-coverage: 65
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/p
          retention-days: 30
